version: '3.7'

services:
  geth-bootnode:
    hostname: geth-bootnode
    env_file:
      - privateChainDocker/.env
    image: geth-client
    build:
      context: ./privateChainDocker
    entrypoint: "bootnode"
    command:
      --nodekey="bootNode.key"
      --addr="172.16.254.2:30301"
      --verbosity=5
    expose:
      - "30301/tcp"
      - "30301/udp"
    volumes:
      - ${PWD}/privateChainDocker/bootNode.key:/usr/src/node/bootNode.key
    networks:
      onepass-vnet:
        ipv4_address: 172.16.254.2

  geth-rpc-client-endpoint:
    hostname: geth-rpc-client-endpoint
    env_file:
      - privateChainDocker/.env
    image: geth-client
    build:
      context: ./privateChainDocker
    depends_on:
      - geth-bootnode
    command:
      --bootnodes=enode://${BOOTNODE}@172.16.254.2:0?discport=30301
      --datadir="node1"
      --port=30307
      --unlock=${NODE1_ACC}
      --password="node1/passNode1"
      --allow-insecure-unlock
      --syncmode="full"
      --ipcdisable
      --networkid=${NETWORK_ID}
      --http
      --http.port=8979
      --http.addr=0.0.0.0
      --http.api="eth,web3,net,txpool"
      --http.corsdomain="*"
      --mine
      --miner.gasprice="0"
      --miner.etherbase=${NODE1_ACC}
    expose:
      - "30307/udp"
      - "30307/tcp"
      - "8979/tcp"
    volumes:
      - ${PWD}/privateChainDocker/node1:/usr/src/node/node1
    networks:
      onepass-vnet:
        ipv4_address: 172.16.254.7

  geth-rpc-admin-endpoint:
    hostname: geth-rpc-admin-endpoint
    env_file:
      - privateChainDocker/.env
    image: geth-admin
    build:
      context: ./privateChainDocker
    depends_on:
      - geth-bootnode
    command:
      --bootnodes=enode://${BOOTNODE}@172.16.254.2:0?discport=30301
      --datadir="node2"
      --port=30308
      --unlock=${NODE2_ACC}
      --password="node2/passNode2"
      --allow-insecure-unlock
      --syncmode="full"
      --ipcdisable
      --http
      --http.port=8980
      --http.addr=0.0.0.0
      --http.api="eth,web3,net,txpool"
      --http.corsdomain="*"
      --networkid=${NETWORK_ID}
      --mine
      --miner.gasprice="0"
      --miner.etherbase=${NODE2_ACC}
    expose:
      - "30308/tcp"
      - "30308/udp"
    ports:
      - "8980:8980/tcp"
    volumes:
      - ${PWD}/privateChainDocker/node2:/usr/src/node/node2
    networks:
      onepass-vnet:
        ipv4_address: 172.16.254.8

  geth-miner-1:
    hostname: geth-miner-1
    env_file:
      - privateChainDocker/.env
    image: geth-client
    build:
      context: ./privateChainDocker
    depends_on:
      - geth-bootnode
    command:
      --datadir="node3"
      --port=30305
      --bootnodes=enode://${BOOTNODE}@172.16.254.2:0?discport=30301
      --unlock=${NODE3_ACC}
      --password="node3/passNode3"
      --syncmode="full"
      --ipcdisable
      --miner.gasprice="0"
      --miner.etherbase=${NODE3_ACC}
      --mine
      --networkid=${NETWORK_ID}
    expose:
      - "30305/udp"
      - "30305/tcp"
    volumes:
      - ${PWD}/privateChainDocker/node3:/usr/src/node/node3
    networks:
      onepass-vnet:
        ipv4_address: 172.16.254.5

  geth-miner-2:
    hostname: geth-miner-2
    env_file:
      - privateChainDocker/.env
    image: geth-client
    build:
      context: ./privateChainDocker
    depends_on:
      - geth-bootnode
    command:
      --datadir="node4"
      --port=30306
      --bootnodes=enode://${BOOTNODE}@172.16.254.2:0?discport=30301
      --unlock=${NODE4_ACC}
      --password="node4/passNode4"
      --syncmode="full"
      --ipcdisable
      --miner.gasprice="0"
      --miner.etherbase=${NODE4_ACC}
      --mine
      --networkid=${NETWORK_ID}
    expose:
      - "30306/udp"
      - "30306/tcp"
    volumes:
      - ${PWD}/privateChainDocker/node4:/usr/src/node/node4
    networks:
      onepass-vnet:
        ipv4_address: 172.16.254.6

networks:
  onepass-vnet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.254.0/28

